[local]
localhost

[mongodb]
mongodb.manikumar.online

[redis]
redis.manikumar.online

[mysql]
mysql.manikumar.online

[rabbitmq]
rabbitmq.manikumar.online

[catalogue]
catalogue.manikumar.online

[user]
user.manikumar.online

[cart]
cart.manikumar.online

[rabbitmq]
rabbitmq.manikumar.online

[shipping]
shipping.manikumar.online

[payment]
payment.manikumar.online

[frontend]
frontend.manikumar.online














