- name: create roboShop system user
  user:
    name: roboShop
    system: true
    home: /app
    shell: /sbin/nologin
    comment: "RoboShop system user"
      
      
- name: remove app directory 
  file:
      path: /app
      state: absent
- name: delete {{ compoent }}.zip
  file:
    path: /tmp/{{ compoent }}.zip
    state: absent
       
- name: create app directory
  file:
    path: /app
    state: directory  
- name: download {{ compoent }}
  get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ compoent }}-v3.zip
    dest: /tmp/{{ compoent }}.zip
- name: unzip {{ compoent }} 
  unarchive:
    src: /tmp/{{ compoent }}.zip
    dest: /app
    remote_src: yes

